version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_8:/var/lib/postgresql/data

  web:
    build:
      context: .
    container_name: app
    command: ["/code/docker_scripts/app.sh"]
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./app:/code/app
      - ./data:/code/data
      - ./scripts:/code/scripts
      - ./images:/code/images
      - ./files:/code/files

  elasticsearch:
    image: elasticsearch:9.3.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - app-network
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  kibana:
    image: kibana:9.3.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app-network
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped


#  java-server:
#    build:
#      context: java-server/.
#    container_name: java-server
#    ports:
#      - "3345:3345"
#    depends_on:
#      - db

volumes:
  postgres_data_8:

networks:
  app-network:
    driver: bridge