FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY scripts /code/scripts
WORKDIR /code

ENTRYPOINT ["python", "/code/scripts/generate.py"]
