"""add image_hash

Revision ID: 767190600c0e
Revises: e392813ea43d
Create Date: 2024-12-02 18:30:46.915740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767190600c0e'
down_revision: Union[str, None] = 'e392813ea43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('image_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'image_hash')
    # ### end Alembic commands ###
