"""change source column

Revision ID: e50af0fcd9cc
Revises: 767190600c0e
Create Date: 2024-12-02 22:17:42.730142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e50af0fcd9cc'
down_revision: Union[str, None] = '767190600c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'source',
               existing_type=postgresql.ENUM('created', 'generated', 'imported', name='todosource'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'source',
               existing_type=sa.String(),
               type_=postgresql.ENUM('created', 'generated', 'imported', name='todosource'),
               existing_nullable=False)
    # ### end Alembic commands ###
