"""Add image_path

Revision ID: 2957b9671fe3
Revises: 62553a9ed760
Create Date: 2024-11-29 19:20:09.243852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2957b9671fe3'
down_revision: Union[str, None] = '62553a9ed760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'image_path')
    # ### end Alembic commands ###
